### ISSUE TITLE
*Everyone read up on their writeup section

### ISSUE THREAD

**Issue by jd1906** [JD760/Team9-UniSim#4]

**Comment by jd1906** [comment]
Write done in the comments once you have read up on your section

**Comment by jd1906** [comment]
https://docs.google.com/document/d/1oFmcSNMvBOqplemytWo9pN6Cml8CWtGO8ueYvgTZtZY/edit

**Comment by WillCroft-4** [comment]
Done

**Comment by jd1906** [comment]
Done
